add_newline = true

# "[WARN] - (starship::utils): Executing command "node" timed out." å¯¾ç­–
# å˜ä½ã¯ãƒŸãƒªç§’
command_timeout = 15000

[hostname]
# bold dimmed green ã ã¨è–„æš—ã (dimmed) ã«ãªã‚‹ã®ã§é™¤å¤–ã™ã‚‹
style = "bold green"

[directory]
truncation_length = 2
# truncation_symbol ãŒæœ‰åŠ¹ã ã¨ truncate_to_repo ã¯ç„¡åŠ¹ï¼ˆã¨ã„ã†ã‹æ„å‘³ãŒãªã„ï¼‰
# truncate_to_repo = true
truncation_symbol = ".../"
# home_symbol = "~/"

[character]
success_symbol = "[ğŸˆ](bg:#800080 fg:#ff1493)" # (bold green)"
error_symbol = "[âŒ](bg:#00ff00 fg:#4b0082)" # (bold red)"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[package]
# ã‚ã¾ã‚Šæœ‰ç”¨ã§ãªã„ã®ã§ disabled ã«ã—ãŸ
disabled = true

[kubernetes]
style = "cyan purple"
symbol = "â›µkube:"
disabled = true

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[nodejs]
symbol = "ğŸ¥Ÿ"
format = '[$symbol($version)]($style) '

[ruby]
symbol = "ğŸ’"
detect_files = ['.ruby-version', 'Gemfile']
format = '[$symbol($version)]($style) '
version_format = 'v${raw}'
detect_extensions = ['rb']

[aws.region_aliases]
ap-northeast-1 = "tokyo"
# ap-northeast-1 = ""

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style) '
style = "bold blue"
symbol = "aws:" # â›…
force_display = true

[gcloud.region_aliases]
asia-northeast1 = "tokyo"

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '
style = "bold green"
symbol = "gcp:" # ğŸŒˆ

[time]
disabled = false
format = 'ğŸ•™[$time]($style) '
utc_time_offset = "local"
time_range = "-"

[git_branch]
symbol = "git:" # ğŸŒ±
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "ğŸ‘"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[username]
style_user = "bold purple"
style_root = "bold red"
format = "[$user]($style) "
disabled = false

[cmd_duration]
min_time = 1_000 # msec
show_milliseconds = false
format = 'å®Ÿè¡Œæ™‚é–“: [$duration]($style) '
style = 'bold yellow'
disabled = false
# ä»¥é™ã®è¡Œã¯ãƒ‡ã‚¹ã‚¯ãƒˆãƒƒãƒ—é€šçŸ¥ã«é–¢ã™ã‚‹è¨­å®š
show_notifications = false
min_time_to_notify = 45_000
# notification_time_out =
