add_newline = true

[directory]
truncation_length = 2
# truncation_symbol ãŒæœ‰åŠ¹ã ã¨ truncate_to_repo ã¯ç„¡åŠ¹ï¼ˆã¨ã„ã†ã‹æ„å‘³ãŒãªã„ï¼‰
# truncate_to_repo = true
truncation_symbol = ".../"
home_symbol = "~/"

[character]
success_symbol = "[ğŸˆ](bold green)"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[nodejs]
symbol = "ï¢˜"

[ruby]
symbol = "ğŸ”º"

[aws.region_aliases]
ap-northeast-1 = "tokyo"

[aws]
style = "bold blue"
symbol = "â˜ï¸ "

[time]
disabled = false
format = 'ğŸ•™[$time]($style) '
utc_time_offset = "local"
time_range = "-"

[git_branch]
symbol = "ğŸŒ±"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

