# $ mkdir -p "$HOME"/.config/mise
# $ cp "$HOME"/dotfiles/initial_scripts_and_settings/settings/mise.toml "$HOME"/.config/mise/config.toml
# $ mise install

# 以下のバージョンは 2025/07/24 現在のものである
[tools]
bun = "1.3.1"
deno = "2.5.6"
flutter = "3.35.7-stable"
go = "1.25.3"
java = "25.0.1+8.0.LTS"
kotlin = "2.2.21"
node = "24.11.0"
rust = "1.91.0"
uv = "0.9.7"

biome = "2.1.3"
pnpm = "10.20.0"
qsv = "6.0.1"
terraform = "1.13.5"

aws-cli = "2.31.30"
circleci = "0.1.32638"
gcloud = "531.0.0"
heroku = "9.5.1"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
