# $ mkdir -p "$HOME"/.config/mise
# $ cp "$HOME"/dotfiles/initial_scripts_and_settings/settings/mise.toml "$HOME"/.config/mise/config.toml
# $ mise install

# 以下のバージョンは 2025/07/24 現在のものである
[tools]
bun = "1.3.8"
deno = "2.6.7"
flutter = "3.38.9-stable"
go = "1.25.6"
java = "25.0.2+10.0.LTS"
kotlin = "2.3.0"
node = "24.13.0"
rust = "1.93.0"
uv = "0.9.28"

biome = "2.1.3"
pnpm = "10.28.2"
qsv = "6.0.1"
terraform = "1.14.4"

aws-cli = "2.33.12"
circleci = "0.1.32638"
gcloud = "531.0.0"
heroku = "9.5.1"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
